define build_elf64_to_32 =
	$(call build_cmd,ELF32,,$(1).elf32,\
        $(SCRIPTS_DIR)/elf64_to_32.py $(1))
endef

define build_ukreloc =
	$(call build_cmd,UKRELOC,,$(1).uk_reloc.bin,\
		$(SCRIPTS_DIR)/mkukreloc.py $(1) && \
		$(OBJCOPY) --update-section .uk_reloc=$(1).uk_reloc.bin $(1) 2>&1 | \
		{ grep -v "section.*lma.*adjusted to.*" || true; })
endef
