define build_elf64_to_32 =
	$(call build_cmd,ELF32,,$(1).elf32,\
		$(SCRIPTS_DIR)/elf64_to_32.py $(1) -o $(1).elf32)
endef

define build_ukreloc =
	$(call build_cmd,UKRELOC,,$(1).uk_reloc.bin,\
		$(SCRIPTS_DIR)/mkukreloc.py $(1) && \
		$(OBJCOPY) --update-section .uk_reloc=$(1).uk_reloc.bin $(1) 2>&1 | \
		{ grep -v "section.*lma.*adjusted to.*" || true; })
endef

BINFO_FLAGS := -a $(CONFIG_UK_ARCH)

ifeq ($(CONFIG_UKPLAT_MEMRNAME),y)
BINFO_FLAGS += -n
endif

define build_bootinfo =
	$(call build_cmd,UKBI,,$(1).bootinfo,\
		$(SCRIPTS_DIR)/mkbootinfo.py $(1) $(1).bootinfo $(BINFO_FLAGS) && \
		$(OBJCOPY) $(1) --update-section .uk_bootinfo=$(1).bootinfo)
endef

define build_efi =
	$(call build_cmd,EFI,,$(1).efi,\
		$(SCRIPTS_DIR)/mkefi.py $(1))
endef
